inherit_gem:
  armitage-rubocop:
    - lib/rubocop.general.yml
    - lib/rubocop.rake.yml
    - lib/rubocop.rspec.yml

AllCops:
  TargetRubyVersion: 3.4.5
  NewCops: enable
  Include:
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
    - graphql-client.gemspec
